baseURL = 'https://blog.andho.xyz/'
languageCode = 'en-us'
title = 'Hi, Im Andho'
theme = 'm10c'

[params]
  autho = 'Andho Mohamed'
  description = 'Im a software developer from the Maldives. Passionate about building beautiful systems on the inside.'
